M48
; DRILL file {KiCad 7.0.10} date Thu 07 Mar 2024 01:06:09 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-07T13:06:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.0395Y-4.4544
X4.2305Y-4.4544
T2
X4.0277Y-4.3351
X4.2423Y-4.3351
T3
X3.215Y-4.405
X3.215Y-7.285
X5.055Y-4.405
X5.055Y-7.285
M30
