M48
; DRILL file {KiCad 8.0.1} date 2024-04-04T17:18:12-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-04T17:18:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.0045Y-3.6393
X4.1955Y-3.6393
T2
X3.9927Y-3.52
X4.2073Y-3.52
T3
X3.175Y-3.6
X3.175Y-8.2
X5.025Y-3.6
X5.025Y-8.2
M30
